### ISSUE TITLE
Elaboração do Relatório dos metodos para medição da fluencia de leitura

### ISSUE THREAD

**Issue by wylli** [AlfaBD/ibpl-alfa-bd-2021#135]
Compilar relatório dos metodos #134 para medição da fluencia de leitura

**Comment by gilliadriano** [comment]
Relatório de métodos para medição da fluência de leitura disponível em:
https://drive.google.com/file/d/1IV13RisdtnjZTyad6AeWbUDfXanaLyHT/view

**Comment by wylli** [comment]
Relatório elaborado e disponibilizado no link abaixo:

https://drive.google.com/file/d/1eWpMu1WZyrQO_LKiOp3faR1AQuWR94MO/view?usp=sharing
