### ISSUE TITLE
US#108 - Documentar

### ISSUE THREAD

**Issue by luanhsd** [AlfaBD/ibpl-alfa-bd-2021#17]
COMO Scrum Master DESEJO QUE seja definido as funcionalidades PARA o perfil Escola

**Comment by cunhaecp** [comment]
Funcionalidades para o Perfil Escola:

https://docs.google.com/document/d/1fC8LPwjyNUB_ah1T7wR8KZjzxoC_e9H9zeCEYupevEM/edit#
