### ISSUE TITLE
US#108 - Levantar os requisitos do perfil Escola

### ISSUE THREAD

**Issue by luanhsd** [AlfaBD/ibpl-alfa-bd-2021#18]
COMO Scrum Master DESEJO QUE seja definido as funcionalidades PARA o perfil Escola

**Comment by cunhaecp** [comment]
Boa tarde @ViniPLippi e @engcompjuliana 
Para essa task, já temos algum requisito para o perfil escola?

Se já tiverem, podem compartilhar aqui? Eu gostaria de ajudar nessa task.

**Comment by cunhaecp** [comment]
Acrescentei a possibilidade de realizar Busca/Pesquisa (_searching_) de Escola.
