### ISSUE TITLE
US#103b - Implementar a prototipação

### ISSUE THREAD

**Issue by luanhsd** [AlfaBD/ibpl-alfa-bd-2021#21]
COMO Backup do Product Owner DESEJO QUE seja feito um prototipo da interface de cadastro de escola PARA criação de um novo usuário no sistema

**Comment by joaosilvajpts** [comment]
Foi feita a prototipação do Cadastro de escola com os seguintes campos:
Nome da Escola
Categoria (Publica ou privada)
Ensino (Fundamental I, Fundamental II ou Médio)
CNPJ
CEP
Dependência (Estadual ou Municipal)
Endereço
Localização (Rural ou Urbana)
Código INEP (Pode ser usado como Primary Key)
Telefone

**Comment by cunhaecp** [comment]
@joaosilvajpts , consegue anexar um print da tela de cadastro escola aqui na task?

**Comment by joaosilvajpts** [comment]
[CADASTRO ESCOLA.pdf](https://github.com/AlfaBD/ibpl-alfa-bd-2021/files/6346737/CADASTRO.ESCOLA.pdf)

Segue o anexo.
