### ISSUE TITLE
Interação com os demais TS para alinhamento de integração do dashboard de professores. (1)

### ISSUE THREAD

**Issue by gilliadriano** [AlfaBD/ibpl-alfa-bd-2021#215]

**Comment by wylli** [comment]
Em contato com o PO Fábio Antônio e a Desenvolvedora Aline, do TS03, ficou entendido que:

Dados foram inseridos no MySQL e no MongoDB para integração com .o Dashboard.
O conteúdo de atividades com os bancos relacionais e não somente relacionais serão disponibilizados no repositório para análise dos demais times.
