### ISSUE TITLE
Entrevistar o PO e Stackeholders para entendimento do que se espera com essa solicitação (1)

### ISSUE THREAD

**Issue by gilliadriano** [AlfaBD/ibpl-alfa-bd-2021#219]

**Comment by wylli** [comment]
Dados da US#223:
1. O quê: Análise descritiva de uso do Apache Spark
2. Para quê: O Dashboard dos professores possa conter dados analíticos

Na entrevista responder às seguintes dúvidas:

1. O quê se deseja analisar?
2. Dos valores a serem analisados, os stackeholders possuem alguma preferência de grafo e uma sugestão de como apresentá-los?

**Comment by wylli** [comment]
Em contato com o PO Fábio Antônio e a Desenvolvedora Aline, do TS03, ficou entendido que:

1. Dados foram inseridos no MySQL e no MongoDB como o primeiro passo para análise desses dados.
2. O conteúdo de atividades com os bancos relacionais, não somente relacionais e spark serão disponibilizados no repositório para análise dos demais times.
