### ISSUE TITLE
Estudar Apache Spark para elaboração do relatório descritivo (4)

### ISSUE THREAD

**Issue by gilliadriano** [AlfaBD/ibpl-alfa-bd-2021#220]

**Comment by wylli** [comment]
API unificada vasta com as operações:

- Ordenar
- agrupar
- filtrar
- selecionar campo
- criar função de:

    - machine learning
    - operação em grafo
    - janelar dado no tempo

**Comment by wylli** [comment]
Estudos tem como referência o seguinte canal no youtube:

https://www.youtube.com/c/CursodeBigData1/videos
