### ISSUE TITLE
Levantar REQUISITOS para o perfil ALUNO (4)

### ISSUE THREAD

**Issue by thiagolopes97** [AlfaBD/ibpl-alfa-bd-2021#55]
Levantar **REQUISITOS** para o perfil **ALUNO**

Atributos levantados (Provisório e dependente dos outros grupos):
- idAluno (ID Usuário do Aluno)
- first_name
- last_name
- CPF
- gender
- status (Ativo/ Inativo)
- resp_first_name (1º Nome do Responável)
- resp_sec_name (Sobrenome Responsável)
- resp_CPF
- resp_phone
- resp_email
- resp_password
- Escola_id
- Turma_id
- Professor_id

**Comment by thiagolopes97** [comment]
Comentário 1 - *Exemplo*

**Comment by Adelmoliveira** [comment]
Requisito 001:
O sistema deverá permitir o cadastro dos dados pessoais dos alunos com a possibilidade de inclusão, consulta, alteração e exclusão dos atributos: Nome, Data de Nascimento (DN), Endereço, Telefone, E-mail, Nacionalidade, Cidade, Estado.

Requisito 002:
O Sistema deverá permitir que o aluno altere seu cadastro.

Requisito 003:
O Aluno poderá realizar consultas as notas e ao seu desempenho.
