### ISSUE TITLE
Modelagem do BD de Cadastro (3)

### ISSUE THREAD

**Issue by jeanclaudio13** [AlfaBD/ibpl-alfa-bd-2021#57]
**MODELAGEM DO BANCO DE DADOS**

Modelagem do banco de dados para o cadastro de novos alunos

"COMO Backup do Product Owner DESEJO QUE seja feito um protótipo da interface de cadastro de aluno PARA criação de um novo usuário no sistema"

**Comment by fdutra04** [comment]
Criei um branch com o arquivo do modelo entidade relacionamento do BD para o cadastro do aluno.
https://github.com/AlfaBD/ibpl-alfa-bd-2021/tree/time-1/modelagemaluno
