### ISSUE TITLE
Criar cenários de testes (2)

### ISSUE THREAD

**Issue by jeanclaudio13** [AlfaBD/ibpl-alfa-bd-2021#58]
Criar 5 +/- 2 Casos de Testes para a US

**Comment by Adelmoliveira** [comment]
Test Case 001
Nome: Cadastrar um aluno
Pré-Condições: Aluno ainda não cadastrado
Procedimentos:
- [ ] Abra a aplicação
- [ ] Clique na aba aluno
- [ ] **Preencha os campos :**
- [ ] Nome completo;
- [ ] Data de Nascimento;
- [ ] CPF;
- [ ] Telefone;
- [ ] E-mail;
- [ ] Sexo;
- [ ] Responsável;
- [ ] Escola;
- [ ] Nº Matricula;
- [ ] Clique no botão cadastrar
-------------------------------------------------------------------------------------------------

**Comment by fdutra04** [comment]
Dá uma olhada nesse arquivo que o professor disponibilizou: https://drive.google.com/file/d/1jZ10M1PR9b8LT_lA8KcfRADvDkBXL7tL/view?usp=sharing

**Comment by fdutra04** [comment]
Eu acho que está bom, só colocar naquele template de casos de teste

**Comment by Adelmoliveira** [comment]
Link para a planilha de Execução de Testes
https://docs.google.com/spreadsheets/d/18wgjOlUifnATdoufeOALQyqqXVXQCbJc7a4KEL6ARK4/edit#gid=1778864658
