### ISSUE TITLE
DOCUMENTAR as funcionalidades (4)

### ISSUE THREAD

**Issue by jeanclaudio13** [AlfaBD/ibpl-alfa-bd-2021#64]
**DOCUMENTAR** as funcionalidades

**Comment by Adelmoliveira** [comment]
Levantar Requisitos do Aluno:
Ferramenta colaborativa by time Professor:
https://app.diagrams.net/#G1Ea4G6_lIzJb3y9UxpZM1C4cxZBhC0EVD

**Comment by Adelmoliveira** [comment]
![Aluno Untitled Diagram](https://user-images.githubusercontent.com/29631438/114720406-608eb400-9d0e-11eb-98ce-92fa2a696988.jpg)

**Comment by fdutra04** [comment]
Excelente, acho que está muito bom.
