### ISSUE TITLE
Mock captura de áudio (1)

### ISSUE THREAD

**Issue by jeanclaudio13** [AlfaBD/ibpl-alfa-bd-2021#69]
Criação da tela para captura do áudio

**Comment by Daniloeng** [comment]
Criação de protótopo de funcionalidade de atividade de leitura por meio de gravação de audio.

[Mockup Alfa-BD Aluno](https://xd.adobe.com/view/e4edc2c5-e8c1-48d7-87c0-99f263b7f657-b1be/?fullscreen)
