### ISSUE TITLE
Criar cenário de teste p/ áudio (3)

### ISSUE THREAD

**Issue by jeanclaudio13** [AlfaBD/ibpl-alfa-bd-2021#73]
Criar 5+-2 cenários de teste

**Comment by Adelmoliveira** [comment]
**Test Case**
O sistema deve permitir que o aluno grave o áudio;
O sistema deve permitir que o aluno apague o áudio e grave novamente;
Ao excluir áudio o Sistema deve ser exibido uma caixa de dialogo pedindo confirmação da exclusão;
O sistema Não deve permitir que o áudio seja maior que x min; e
O Aluno Poderá ouvir o áudio gravado.

**Test Steps**
1) Verificar se uma mensagem foi exibida após agravação do áudio;
2) Verificar se a opção gravar novamente aparece para o aluno;
3) Verificar se existe uma confirmação de delete de áudio;

**What To Expect**
Que o áudio seja  gravado e salvo em um BD relacional
