### ISSUE TITLE
Mock para a view de Cadastro (1)

### ISSUE THREAD

**Issue by jeanclaudio13** [AlfaBD/ibpl-alfa-bd-2021#75]
Criar **mock** para a view de Cadastro

xdAdobe:

https://xd.adobe.com/view/1c60d033-489f-43a4-bdb4-83fbd4a7283e-4933/

**Comment by Daniloeng** [comment]
Foi realizada a criação do mockup de interface, que pode ser acessada pelo link a seguir

[Alfa-BD - Alunos](https://xd.adobe.com/view/1c60d033-489f-43a4-bdb4-83fbd4a7283e-4933/)
